import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ERP App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-3 border-b-2  border-slate-50">
          <div className="container mx-auto flex justify-between items-center">
            <div className="flex items-center w-1/4">
              <div className="w-4 h-4 bg-gray-300 rounded-full flex items-center justify-center p-4"></div>
              <div className="pl-4">
                <Link className="hover:text-blue-500" href="/">
                  Home
                </Link>
              </div>
            </div>
            <div className=" flex justify-between gap-4">
              <div>
                <Link className="hover:text-blue-500" href="/auth/login">
                  Login
                </Link>
              </div>
              <div>
                <Link className="hover:text-blue-500" href="/auth/signup">
                  Signup
                </Link>
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
